package model

import "time"

// Config holds all configuration for Entropia
type Config struct {
	// HTTP Settings
	HTTP HTTPConfig `json:"http" yaml:"http"`

	// Concurrency Settings
	Concurrency ConcurrencyConfig `json:"concurrency" yaml:"concurrency"`

	// Rate Limiting
	RateLimiting RateLimitingConfig `json:"rate_limiting" yaml:"rate_limiting"`

	// Cache Settings
	Cache CacheConfig `json:"cache" yaml:"cache"`

	// LLM Settings
	LLM LLMConfig `json:"llm" yaml:"llm"`

	// Scoring Settings
	Scoring ScoringConfig `json:"scoring" yaml:"scoring"`

	// Output Settings
	Output OutputConfig `json:"output" yaml:"output"`

	// Authority Classification
	Authority AuthorityConfig `json:"authority" yaml:"authority"`
}

// HTTPConfig contains HTTP client settings
type HTTPConfig struct {
	Timeout         time.Duration `json:"timeout" yaml:"timeout"`                   // Request timeout
	UserAgent       string        `json:"user_agent" yaml:"user_agent"`             // User-Agent header
	FollowRedirects bool          `json:"follow_redirects" yaml:"follow_redirects"` // Whether to follow redirects
	MaxRedirects    int           `json:"max_redirects" yaml:"max_redirects"`       // Max redirects to follow
	MaxBodyBytes    int64         `json:"max_body_bytes" yaml:"max_body_bytes"`     // Max response size
	InsecureTLS     bool          `json:"insecure_tls" yaml:"insecure_tls"`         // Skip TLS certificate verification
	HTTPProxy       string        `json:"http_proxy" yaml:"http_proxy"`             // HTTP proxy URL (overrides HTTP_PROXY env var)
	HTTPSProxy      string        `json:"https_proxy" yaml:"https_proxy"`           // HTTPS proxy URL (overrides HTTPS_PROXY env var)
	NoProxy         string        `json:"no_proxy" yaml:"no_proxy"`                 // Comma-separated hosts to bypass proxy
}

// ConcurrencyConfig contains concurrency settings
type ConcurrencyConfig struct {
	Workers           int `json:"workers" yaml:"workers"`                       // Batch mode workers
	ValidationWorkers int `json:"validation_workers" yaml:"validation_workers"` // Concurrent evidence validation
}

// RateLimitingConfig contains rate limiting settings
type RateLimitingConfig struct {
	RequestsPerSecond float64 `json:"requests_per_second" yaml:"requests_per_second"` // Rate limit per domain
	RespectRobotsTxt  bool    `json:"respect_robots_txt" yaml:"respect_robots_txt"`   // Respect robots.txt
	BurstSize         int     `json:"burst_size" yaml:"burst_size"`                   // Burst allowance
}

// CacheConfig contains cache settings
type CacheConfig struct {
	Enabled bool          `json:"enabled" yaml:"enabled"` // Enable caching
	TTL     time.Duration `json:"ttl" yaml:"ttl"`         // Cache TTL
	Dir     string        `json:"dir" yaml:"dir"`         // Cache directory
}

// LLMConfig contains LLM provider settings
type LLMConfig struct {
	Provider       string `json:"provider" yaml:"provider"`               // openai, anthropic, ollama, ""
	Model          string `json:"model" yaml:"model"`                     // Model name
	APIKey         string `json:"api_key" yaml:"api_key"`                 // API key (or env var name)
	BaseURL        string `json:"base_url" yaml:"base_url"`               // For Ollama/custom endpoints
	StrictEvidence bool   `json:"strict_evidence" yaml:"strict_evidence"` // Enforce citation allowlist
	Timeout        int    `json:"timeout" yaml:"timeout"`                 // LLM request timeout (seconds)
	MaxTokens      int    `json:"max_tokens" yaml:"max_tokens"`           // Max output tokens
	HTTPProxy      string `json:"http_proxy" yaml:"http_proxy"`           // HTTP proxy URL
	HTTPSProxy     string `json:"https_proxy" yaml:"https_proxy"`         // HTTPS proxy URL
	NoProxy        string `json:"no_proxy" yaml:"no_proxy"`               // Comma-separated hosts to bypass proxy
}

// ScoringConfig contains scoring engine settings
type ScoringConfig struct {
	RulesFile string `json:"rules_file" yaml:"rules_file"` // Path to custom scoring rules JSON
}

// OutputConfig contains output settings
type OutputConfig struct {
	Format        string `json:"format" yaml:"format"`                 // json, markdown, both
	Dir           string `json:"dir" yaml:"dir"`                       // Output directory
	Verbose       bool   `json:"verbose" yaml:"verbose"`               // Verbose output
	IncludeFooter bool   `json:"include_footer" yaml:"include_footer"` // Include "Generated by Entropia" footer
}

// AuthorityConfig contains authority classification settings
type AuthorityConfig struct {
	PrimaryDomains   []string          `json:"primary_domains" yaml:"primary_domains"`     // Tier 1 domain allowlist
	SecondaryDomains []string          `json:"secondary_domains" yaml:"secondary_domains"` // Tier 2 domain allowlist
	PathPatterns     []PathPattern     `json:"path_patterns" yaml:"path_patterns"`         // URL path-based rules
	DomainMap        map[string]string `json:"domain_map" yaml:"domain_map"`               // Explicit domain → tier mapping
}

// PathPattern defines a URL path pattern for authority classification
type PathPattern struct {
	Pattern string `json:"pattern" yaml:"pattern"` // Regex pattern
	Tier    string `json:"tier" yaml:"tier"`       // primary, secondary, tertiary
}

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		HTTP: HTTPConfig{
			Timeout:         30 * time.Second,
			UserAgent:       "Entropia/0.1 (+https://github.com/ppiankov/entropia)",
			FollowRedirects: true,
			MaxRedirects:    3,
			MaxBodyBytes:    2_000_000, // 2MB
		},
		Concurrency: ConcurrencyConfig{
			Workers:           4,  // Default: runtime.NumCPU() in actual implementation
			ValidationWorkers: 20, // I/O bound, can be higher
		},
		RateLimiting: RateLimitingConfig{
			RequestsPerSecond: 2.0,
			RespectRobotsTxt:  true,
			BurstSize:         5,
		},
		Cache: CacheConfig{
			Enabled: true,
			TTL:     24 * time.Hour,
			Dir:     "~/.entropia/cache",
		},
		LLM: LLMConfig{
			Provider:       "", // Disabled by default
			Model:          "gpt-4o-mini",
			StrictEvidence: true, // Always enforce by default
			Timeout:        20,
			MaxTokens:      500,
		},
		Scoring: ScoringConfig{
			RulesFile: "", // Use built-in rules
		},
		Output: OutputConfig{
			Format:        "both", // JSON + Markdown
			Dir:           "./entropia-reports",
			Verbose:       false,
			IncludeFooter: true, // Include "Generated by Entropia" footer by default
		},
		Authority: AuthorityConfig{
			PrimaryDomains: []string{
				"legislation.gov.uk",
				"doi.org",
				"scholar.google.com",
				"jstor.org",
				"arxiv.org",
			},
			SecondaryDomains: []string{
				"wikipedia.org",
				"britannica.com",
				"nytimes.com",
				"bbc.com",
			},
			PathPatterns: []PathPattern{
				{Pattern: "/statute/", Tier: "primary"},
				{Pattern: "/legal/", Tier: "primary"},
				{Pattern: "/law/", Tier: "primary"},
			},
			DomainMap: make(map[string]string),
		},
	}
}
