package llm

import (
	"context"
	"fmt"

	"github.com/ppiankov/entropia/internal/model"
)

// Summarizer generates LLM summaries for Entropia reports
type Summarizer struct {
	provider Provider
	config   Config
}

// NewSummarizer creates a new summarizer with the specified provider
func NewSummarizer(config Config) (*Summarizer, error) {
	// Create provider
	provider, err := NewProvider(config)
	if err != nil {
		return nil, fmt.Errorf("create provider: %w", err)
	}

	// If provider is nil, LLM is disabled
	if provider == nil {
		return &Summarizer{
			provider: nil,
			config:   config,
		}, nil
	}

	return &Summarizer{
		provider: provider,
		config:   config,
	}, nil
}

// GenerateSummary generates an LLM summary for a report with strict evidence mode
// Returns nil if LLM is disabled (provider is nil)
func (s *Summarizer) GenerateSummary(ctx context.Context, report model.Report) (*model.LLMSummary, error) {
	// If no provider, return nil (LLM disabled)
	if s.provider == nil {
		return nil, nil
	}

	// Check if provider is available
	if !s.provider.IsAvailable(ctx) {
		return &model.LLMSummary{
			Enabled: false,
			Warnings: []string{
				fmt.Sprintf("LLM provider %s is not available", s.provider.Name()),
			},
		}, nil
	}

	// Extract evidence URLs for strict mode
	evidenceURLs := make([]string, len(report.Evidence))
	for i, ev := range report.Evidence {
		evidenceURLs[i] = ev.URL
	}

	// Create summarize request
	req := SummarizeRequest{
		Report:       report,
		EvidenceURLs: evidenceURLs,
		Prompt:       "", // Use default prompt
		Model:        s.config.Model,
		MaxTokens:    s.config.MaxTokens,
	}

	// Call provider
	resp, err := s.provider.Summarize(ctx, req)
	if err != nil {
		// Return error as warning, don't fail the entire scan
		return &model.LLMSummary{
			Enabled:        true,
			Provider:       s.provider.Name(),
			Model:          s.config.Model,
			StrictEvidence: s.config.StrictEvidence,
			Warnings: []string{
				fmt.Sprintf("LLM summary generation failed: %v", err),
			},
		}, nil
	}

	// Build successful summary
	summary := &model.LLMSummary{
		Enabled:        true,
		Provider:       s.provider.Name(),
		Model:          resp.Model,
		StrictEvidence: s.config.StrictEvidence,
		SummaryMD:      resp.Summary,
		Warnings:       []string{},
	}

	// Add token usage note
	if resp.TokensUsed > 0 {
		summary.Warnings = append(summary.Warnings, fmt.Sprintf("Tokens used: %d", resp.TokensUsed))
	}

	// Add citation verification note
	if len(resp.CitedURLs) > 0 {
		summary.Warnings = append(summary.Warnings, fmt.Sprintf("Verified %d citations against evidence allowlist", len(resp.CitedURLs)))
	}

	return summary, nil
}

// RenderSeparateMarkdown generates a separate Markdown file for LLM summary
// This clearly separates LLM output from core Entropia analysis
func RenderSeparateMarkdown(summary *model.LLMSummary) string {
	if summary == nil || !summary.Enabled {
		return ""
	}

	md := "# LLM Summary\n\n"
	md += "**⚠️ GENERATED CONTENT**: This summary was generated by a large language model and is provided for convenience only. It does not affect Entropia's scoring or analysis.\n\n"

	md += fmt.Sprintf("- **Provider**: %s\n", summary.Provider)
	if summary.Model != "" {
		md += fmt.Sprintf("- **Model**: %s\n", summary.Model)
	}
	md += fmt.Sprintf("- **Strict Evidence Mode**: %t\n", summary.StrictEvidence)
	md += "\n---\n\n"

	if summary.SummaryMD != "" {
		md += summary.SummaryMD + "\n\n"
	} else {
		md += "*No summary generated*\n\n"
	}

	if len(summary.Warnings) > 0 {
		md += "## Notes\n\n"
		for _, warning := range summary.Warnings {
			md += fmt.Sprintf("- %s\n", warning)
		}
	}

	md += "\n---\n\n"
	md += "*This summary was generated to help interpret the Entropia report. All claims, scores, and signals in the main report are determined independently of this LLM output.*\n"

	return md
}

// IsEnabled returns whether the summarizer has a provider configured
func (s *Summarizer) IsEnabled() bool {
	return s.provider != nil
}

// ProviderName returns the name of the configured provider, or empty string if disabled
func (s *Summarizer) ProviderName() string {
	if s.provider == nil {
		return ""
	}
	return s.provider.Name()
}
